### ISSUE TITLE
Error : Failed to get latest data

### ISSUE THREAD

**Issue by CenturionLC** [Rec1dite/espr#1]
![image](https://github.com/Rec1dite/espr/assets/100900058/5e75a3ca-11c7-4093-ae56-d814db6881af)

The toolbar is frequently displaying : "ERR : Failed to get latest data. Code 429"

**Comment by Rec1dite** [comment]
Error 429 is due to the daily API token quota being exceeded.
This problem should be fixable by changing the `refresh` parameter in the `CONFIG` variable (see `configs.py`) to a value of `60` instead.
Espr's error handling is rather poor at the moment, definitely not user friendly. I'll look at making it fail a bit more gracefully with more helpful error info 👍

**Comment by CenturionLC** [comment]
No commits in over a year, literally unusable :/

**Comment by Rec1dite** [comment]
Clearly the software was just perfect from the get-go
